language: python

python:
- 3.6

# Command to install dependencies
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

# Command to run tests
script: coverage run -m unittest discover -v polarTransform/tests

# Command to deploy releases to PyPi
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: addisonElliott
  on:
    tags: true
  password:
    secure: "ZtRj8+DICQJpHuTlAS2M8Sec2otEM9BuwrP7hZ9JH8eiOWyp5ovQRikfxIxBLVycFLWwgB8oe20sAaiXDFlrrUjk5Pg7qzoREfxees0UToEvVI3+O++OWgz25pmvvGmzbheS8RiQVLMIA32fgV6GgodkN7NzDclp3sN3BzakaRqBuny3qJQO5qSVhBWHptEsxrQlATYGKAIUqrMDEOlYfv2Crpf0g3MT7r90mD43t6z2s5Crkyf7WTG8jQtAsyUIPJVK68ljcgaAom8iFM3Jp7EucrGBuqd7mN1QHPCGDFIwN/RxWi2nUkcDL1rjadxdiIammMy6OnLz/UmpVcoEZmY3bQeXpySlMhco6RCW+t3MaGYC60iGYvG1aTV7VsLuKZ4y7tsNIbaI96iilQfcdVVZsydmJkr3jI1ySDQE6tyrrYR2CNsuRhEZkTGgOoTjXFuJSi5C+YREZH1wnoEFxrq5iiNJEppql93xMWumjwN8Cgdy144ysLTcZmC2bVd8tRLChBCgEPqsJl/A1R6cDuYufmSl22wnd7UekazcjIEqR2kaX2Clz+PaOZEdc2JiLF7R0uuUGKCba6ds8UqFrsNyOXS5URQsvqLgxu597lI3lABHmcbqLsv28uurfvLLV1oeiQUKrqAHuinVPy2waAgSGCKz0sB3qduS95PxLDc="

after_success:
  - codecov

# Only build for master branch and tagged released (must follow semantic versioning syntax)
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/



